spring:
        datasource:
          url: jdbc:mysql://180.76.55.189:3308/study?useUnicode&characterEncoding=utf-8
          username: jziyy
          password: q8048010
          driver-class-name: com.mysql.jdbc.Driver
        application:
          name: spring-boot-rabbitmq
        rabbitmq:
          host: 180.76.55.189
          port: 5672
          username: jziyy
          password: q80480
server:
  port: 9090